import 'package:flutter/material.dart';

class CoinData {
  final String name;
  final String symbol;
  final String iconChar;
  final double price;
  final double changePercent;
  final double holdings;
  final List<double> sparkline;
  final Color accentColor;

  const CoinData({
    required this.name,
    required this.symbol,
    required this.iconChar,
    required this.price,
    required this.changePercent,
    required this.holdings,
    required this.sparkline,
    required this.accentColor,
  });
}

class Transaction {
  final String title;
  final String subtitle;
  final double amount;
  final bool isIncoming;
  final String time;
  final IconData icon;

  const Transaction({
    required this.title,
    required this.subtitle,
    required this.amount,
    required this.isIncoming,
    required this.time,
    required this.icon,
  });
}

class MockData {
  MockData._();

  static const String walletAddress =
      '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18';

  static const double totalBalance = 24563.82;
  static const double totalChangePercent = 3.42;

  static const List<CoinData> coins = [
    CoinData(
      name: 'Bitcoin',
      symbol: 'BTC',
      iconChar: '₿',
      price: 67432.15,
      changePercent: 2.34,
      holdings: 0.245,
      sparkline: [
        64000,
        65200,
        64800,
        66100,
        65500,
        67000,
        66800,
        67432,
        67100,
        67800,
        67200,
        67432,
      ],
      accentColor: Color(0xFFF7931A),
    ),
    CoinData(
      name: 'Ethereum',
      symbol: 'ETH',
      iconChar: 'Ξ',
      price: 3521.87,
      changePercent: 4.12,
      holdings: 2.5,
      sparkline: [
        3200,
        3350,
        3280,
        3400,
        3380,
        3450,
        3420,
        3500,
        3480,
        3520,
        3510,
        3521,
      ],
      accentColor: Color(0xFF627EEA),
    ),
    CoinData(
      name: 'Solana',
      symbol: 'SOL',
      iconChar: '◎',
      price: 178.43,
      changePercent: -1.56,
      holdings: 45.0,
      sparkline: [190, 185, 188, 182, 180, 183, 179, 178, 181, 177, 179, 178],
      accentColor: Color(0xFF9945FF),
    ),
  ];

  static const List<Transaction> recentTransactions = [
    Transaction(
      title: 'Received Bitcoin',
      subtitle: 'From 0x3a...f82d',
      amount: 0.015,
      isIncoming: true,
      time: '2 min ago',
      icon: Icons.arrow_downward_rounded,
    ),
    Transaction(
      title: 'Sent Ethereum',
      subtitle: 'To 0x8b...c4e1',
      amount: 0.5,
      isIncoming: false,
      time: '1 hr ago',
      icon: Icons.arrow_upward_rounded,
    ),
    Transaction(
      title: 'Received Solana',
      subtitle: 'From 0xf1...a923',
      amount: 12.0,
      isIncoming: true,
      time: '3 hrs ago',
      icon: Icons.arrow_downward_rounded,
    ),
    Transaction(
      title: 'Swap ETH → SOL',
      subtitle: 'Via DEX Aggregator',
      amount: 1.2,
      isIncoming: false,
      time: '5 hrs ago',
      icon: Icons.swap_horiz_rounded,
    ),
    Transaction(
      title: 'Received Bitcoin',
      subtitle: 'From 0xd4...b7f5',
      amount: 0.032,
      isIncoming: true,
      time: 'Yesterday',
      icon: Icons.arrow_downward_rounded,
    ),
  ];

  static const List<String> seedSuggestions = [
    'abandon',
    'ability',
    'able',
    'about',
    'above',
    'absent',
    'absorb',
    'abstract',
    'absurd',
    'abuse',
    'access',
    'accident',
    'account',
    'accuse',
    'achieve',
    'acid',
    'acoustic',
    'acquire',
    'across',
    'act',
    'action',
    'actor',
    'actual',
    'adapt',
    'add',
    'addict',
    'address',
    'adjust',
    'admit',
    'adult',
    'advance',
    'advice',
    'aerobic',
    'affair',
    'afford',
    'afraid',
    'again',
    'age',
    'agent',
    'agree',
    'ahead',
    'aim',
    'air',
    'airport',
    'aisle',
    'alarm',
    'album',
    'alcohol',
    'alert',
    'alien',
    'all',
    'alley',
    'allow',
    'almost',
    'alone',
    'alpha',
    'already',
    'also',
    'alter',
    'always',
    'amount',
    'amused',
    'analyst',
    'anchor',
    'ancient',
    'anger',
    'angle',
    'angry',
    'animal',
    'ankle',
    'announce',
    'annual',
    'another',
    'answer',
    'antenna',
    'antique',
    'anxiety',
    'any',
    'apart',
    'apology',
    'appear',
    'apple',
    'approve',
    'april',
    'arch',
    'arctic',
    'area',
    'arena',
    'argue',
    'arm',
    'armor',
    'army',
    'arrange',
    'arrest',
    'arrive',
    'arrow',
    'art',
    'asset',
    'assist',
    'atom',
    'audit',
    'august',
    'aunt',
    'auto',
    'autumn',
    'average',
    'avocado',
    'avoid',
    'awake',
    'aware',
    'awesome',
    'awful',
    'awkward',
    'axis',
    'baby',
    'bachelor',
    'bacon',
    'badge',
    'bag',
    'balance',
    'balcony',
    'ball',
    'bamboo',
    'banana',
    'banner',
    'bar',
    'bargain',
    'barrel',
    'base',
    'basic',
    'basket',
    'battle',
    'beach',
    'bean',
    'beauty',
    'because',
    'become',
    'beef',
    'begin',
    'below',
    'bench',
    'benefit',
    'best',
    'betray',
    'beyond',
    'bird',
    'bitter',
    'blade',
    'blanket',
    'blast',
    'bleak',
    'blind',
    'blood',
    'blossom',
    'blue',
    'blur',
    'blush',
    'board',
    'boat',
    'body',
    'bomb',
    'bone',
    'bonus',
    'book',
    'boost',
    'border',
    'boring',
    'borrow',
    'boss',
    'bottom',
    'bounce',
    'box',
    'boy',
    'bracket',
    'brain',
    'brand',
    'brave',
    'bread',
    'breeze',
    'brick',
    'bridge',
    'brief',
    'bright',
    'bring',
    'brisk',
    'broken',
    'bronze',
    'broom',
    'brother',
    'brown',
    'brush',
    'bubble',
    'buddy',
    'budget',
    'buffalo',
    'build',
    'bulb',
    'bulk',
    'bundle',
    'burden',
    'burger',
    'burst',
    'bus',
    'butter',
    'buyer',
    'cabin',
    'cable',
    'cactus',
    'cage',
    'cake',
    'call',
    'calm',
    'camera',
    'camp',
    'canal',
    'cancel',
    'candy',
    'cannon',
    'canoe',
    'canvas',
    'canyon',
    'capable',
    'capital',
    'captain',
    'carbon',
    'card',
    'cargo',
    'carpet',
    'carry',
    'cart',
    'case',
    'castle',
    'casual',
    'catalog',
    'catch',
    'category',
    'cattle',
    'ceiling',
    'celery',
    'cement',
    'census',
    'century',
    'cereal',
    'certain',
    'chair',
    'chalk',
    'champion',
    'change',
    'chaos',
    'chapter',
    'charge',
    'chase',
    'cheap',
    'check',
    'cheese',
    'cherry',
    'chest',
    'chicken',
    'chief',
    'child',
    'chimney',
    'choice',
    'chunk',
    'circle',
    'citizen',
    'city',
    'civil',
    'claim',
    'clap',
    'clarify',
    'claw',
    'clean',
    'clerk',
    'clever',
    'click',
    'client',
    'cliff',
    'climb',
    'clinic',
    'clip',
    'clock',
    'close',
    'cloth',
    'cloud',
    'clown',
    'club',
    'clump',
    'cluster',
    'coach',
    'coast',
    'coconut',
    'code',
    'coffee',
    'coil',
    'coin',
    'collect',
    'color',
    'column',
    'combine',
    'come',
    'comfort',
    'comic',
    'common',
    'company',
    'concert',
    'conduct',
    'confirm',
    'congress',
    'connect',
    'consider',
    'control',
    'convince',
    'cook',
    'cool',
    'copper',
    'copy',
    'coral',
    'core',
    'corn',
    'correct',
    'cost',
    'cotton',
    'couch',
    'country',
    'couple',
    'course',
    'cousin',
    'cover',
    'coyote',
    'cradle',
    'craft',
    'cramp',
    'crane',
    'crash',
    'crazy',
    'cream',
    'credit',
    'creek',
    'crew',
    'cricket',
    'crime',
    'crisp',
    'critic',
    'crop',
    'cross',
    'crouch',
    'crowd',
    'crucial',
    'cruel',
    'cruise',
    'crumble',
    'crush',
    'cry',
    'crystal',
    'cube',
    'culture',
    'cup',
    'cupboard',
    'curious',
    'current',
    'curtain',
    'curve',
    'cushion',
    'custom',
    'cute',
    'cycle',
    'dad',
    'damage',
    'damp',
    'dance',
    'danger',
    'daring',
    'dash',
    'daughter',
    'dawn',
    'day',
    'deal',
    'debate',
    'debris',
    'decade',
    'december',
    'decide',
    'decline',
    'decorate',
    'decrease',
    'deer',
    'defense',
    'define',
    'defy',
    'degree',
    'delay',
    'deliver',
    'demand',
    'denial',
    'dentist',
    'deny',
    'depart',
    'depend',
    'deposit',
    'depth',
    'deputy',
    'derive',
    'describe',
    'desert',
    'design',
    'desk',
    'despair',
    'destroy',
    'detail',
    'detect',
    'develop',
    'device',
    'devote',
    'diagram',
    'dial',
    'diamond',
    'diary',
    'diesel',
    'diet',
    'differ',
    'digital',
    'dignity',
    'dilemma',
    'dinner',
    'dinosaur',
    'direct',
    'dirt',
    'disagree',
    'discover',
    'disease',
    'dish',
    'dismiss',
    'disorder',
    'display',
    'distance',
    'divert',
    'divide',
    'divorce',
  ];
}
